# Generated by Django 5.2.8 on 2025-11-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('Quito', 'Quito'), ('Cayambe', 'Cayambe'), ('Ibarra', 'Ibarra'), ('Otavalo', 'Otavalo'), ('Tulcán', 'Tulcán'), ('Latacunga', 'Latacunga'), ('Ambato', 'Ambato'), ('Salcedo', 'Salcedo'), ('Riobamba', 'Riobamba'), ('Guaranda', 'Guaranda'), ('Baños', 'Baños'), ('Cuenca', 'Cuenca'), ('Azogues', 'Azogues'), ('Cañar', 'Cañar'), ('Loja', 'Loja'), ('Zamora', 'Zamora'), ('Macas', 'Macas'), ('Esmeraldas', 'Esmeraldas'), ('Atacames', 'Atacames'), ('Santo Domingo', 'Santo Domingo'), ('Quinindé', 'Quinindé'), ('Manabí', 'Portoviejo'), ('Manta', 'Manta'), ('Chone', 'Chone'), ('El Carmen', 'El Carmen'), ('Guayaquil', 'Guayaquil'), ('Milagro', 'Milagro'), ('Babahoyo', 'Babahoyo'), ('Quevedo', 'Quevedo'), ('Machala', 'Machala'), ('Pasaje', 'Pasaje'), ('Huaquillas', 'Huaquillas'), ('Santa Rosa', 'Santa Rosa'), ('Tena', 'Tena'), ('Puyo', 'Puyo'), ('El Coca', 'El Coca'), ('Lago Agrio', 'Lago Agrio'), ('Sucumbíos', 'Sucumbíos'), ('San Cristóbal', 'San Cristóbal'), ('Santa Cruz', 'Santa Cruz')], max_length=100)),
                ('destino', models.CharField(choices=[('Quito', 'Quito'), ('Cayambe', 'Cayambe'), ('Ibarra', 'Ibarra'), ('Otavalo', 'Otavalo'), ('Tulcán', 'Tulcán'), ('Latacunga', 'Latacunga'), ('Ambato', 'Ambato'), ('Salcedo', 'Salcedo'), ('Riobamba', 'Riobamba'), ('Guaranda', 'Guaranda'), ('Baños', 'Baños'), ('Cuenca', 'Cuenca'), ('Azogues', 'Azogues'), ('Cañar', 'Cañar'), ('Loja', 'Loja'), ('Zamora', 'Zamora'), ('Macas', 'Macas'), ('Esmeraldas', 'Esmeraldas'), ('Atacames', 'Atacames'), ('Santo Domingo', 'Santo Domingo'), ('Quinindé', 'Quinindé'), ('Manabí', 'Portoviejo'), ('Manta', 'Manta'), ('Chone', 'Chone'), ('El Carmen', 'El Carmen'), ('Guayaquil', 'Guayaquil'), ('Milagro', 'Milagro'), ('Babahoyo', 'Babahoyo'), ('Quevedo', 'Quevedo'), ('Machala', 'Machala'), ('Pasaje', 'Pasaje'), ('Huaquillas', 'Huaquillas'), ('Santa Rosa', 'Santa Rosa'), ('Tena', 'Tena'), ('Puyo', 'Puyo'), ('El Coca', 'El Coca'), ('Lago Agrio', 'Lago Agrio'), ('Sucumbíos', 'Sucumbíos'), ('San Cristóbal', 'San Cristóbal'), ('Santa Cruz', 'Santa Cruz')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cooperativa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.ruta')),
            ],
        ),
    ]
