# Generated by Django 5.2.8 on 2025-11-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pasajero', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('asiento', models.PositiveIntegerField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.horario')),
            ],
        ),
    ]
