# Generated by Django 5.2.8 on 2025-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
    ]
