# Generated by Django 5.2.8 on 2025-11-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('reservas', '0002_alter_reserva_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservas', models.JSONField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('propuesta_origen', models.FloatField()),
                ('propuesta_destino', models.FloatField(blank=True, null=True)),
                ('creada_por', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociacion_destino', to='administracion.horario')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociacion_origen', to='administracion.horario')),
            ],
        ),
    ]
