# Generated by Django 5.2.8 on 2025-11-19 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('reservas', '0003_negociacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negociacion',
            old_name='propuesta_origen',
            new_name='costo_por_pasajero',
        ),
        migrations.RenameField(
            model_name='negociacion',
            old_name='propuesta_destino',
            new_name='precio_final',
        ),
        migrations.RemoveField(
            model_name='negociacion',
            name='creada_por',
        ),
        migrations.AddField(
            model_name='negociacion',
            name='comentario_destino',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='negociacion',
            name='comentario_origen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='negociacion',
            name='compensacion_minima',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='negociacion',
            name='costo_operativo_destino',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='negociacion',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neg_destino', to='administracion.horario'),
        ),
        migrations.AlterField(
            model_name='negociacion',
            name='estado',
            field=models.CharField(default='PROPUESTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='negociacion',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neg_origen', to='administracion.horario'),
        ),
    ]
