# Generated by Django 5.2.8 on 2025-11-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_transferida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'permissions': [('can_reactivar', 'Puede reactivar pasajeros transferidos')]},
        ),
    ]
