# Generated by Django 5.2.8 on 2025-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('reservas', '0006_alter_reserva_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('horario', 'asiento'), name='unique_asiento_por_horario'),
        ),
    ]
